context:
  version: "0.8.8"

package:
  name: fselect
  version: ${{ version }}

source:
  url: https://github.com/jhspetersson/fselect/archive/${{ version }}.tar.gz
  sha256: 0f586c3870a66d4a3ab7b92409dcf0f68a23bd8031ec0cc3f1622efebe190c9e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cmake
    - make

tests:
  - script:
      - fselect --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Find files with SQL-like queries
  homepage: https://github.com/jhspetersson/fselect
  repository: https://github.com/jhspetersson/fselect

extra:
  recipe-maintainers:
    - danielnachun
