context:
  version: "0.8.11"

package:
  name: fselect
  version: ${{ version }}

source:
  url: https://github.com/jhspetersson/fselect/archive/${{ version }}.tar.gz
  sha256: aafd7d6463a1d8d699a9d3f80295b66aee1b6dc3748c9409c7b76f5fef9a180c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - fselect --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Find files with SQL-like queries
  homepage: https://github.com/jhspetersson/fselect
  repository: https://github.com/jhspetersson/fselect

extra:
  recipe-maintainers:
    - danielnachun
