context:
  version: "0.8.9"

package:
  name: fselect
  version: ${{ version }}

source:
  url: https://github.com/jhspetersson/fselect/archive/${{ version }}.tar.gz
  sha256: 08a903e2bd7d68dff004a6552dc5823989c74ce20a96416601ce7002f6b51a7b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - openssl
    - if: win
      then:
        - libssh2

tests:
  - script:
      - fselect --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Find files with SQL-like queries
  homepage: https://github.com/jhspetersson/fselect
  repository: https://github.com/jhspetersson/fselect

extra:
  recipe-maintainers:
    - danielnachun
