context:
  version: "0.9.3"

package:
  name: fselect
  version: ${{ version }}

source:
  url: https://github.com/jhspetersson/fselect/archive/${{ version }}.tar.gz
  sha256: ea824bd6e57926e243c98ed2fa73bf3eb412a3bd837c388abb1451d727dc46f2

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - if: unix
      then:
        - openssl
  run:
    - if: win
      then:
        - libgit2

tests:
  - script:
      - fselect --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Find files with SQL-like queries
  homepage: https://github.com/jhspetersson/fselect
  repository: https://github.com/jhspetersson/fselect

extra:
  recipe-maintainers:
    - danielnachun
