context:
  version: "0.10.1"

package:
  name: fselect
  version: ${{ version }}

source:
  url: https://github.com/jhspetersson/fselect/archive/${{ version }}.tar.gz
  sha256: 20425a3ab36fd46b24bb280a3c13187e0b33ab2e68734d8f51b07710af25581f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - if: unix
      then:
        - openssl
  run:
    - if: win
      then:
        - libgit2

tests:
  - script:
      - fselect --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Find files with SQL-like queries
  homepage: https://github.com/jhspetersson/fselect
  repository: https://github.com/jhspetersson/fselect

extra:
  recipe-maintainers:
    - danielnachun
